# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    #    param_fetcher_listener:  true
    #    allowed_methods_listener:  true
    serializer:
        serialize_null: true
    routing_loader:
        include_format: false
    view:
        view_response_listener:  true
    exception:
        enabled: true
        messages:
            'Symfony\Component\HttpKernel\Exception\HttpException' : true
            'Symfony\Component\Security\Core\Exception\BadCredentialsException': true
        codes:
            'Symfony\Component\Security\Core\Exception\BadCredentialsException': 401
    format_listener:
        rules:
            - { path: ^/api, fallback_format: 'json', priorities: [ 'json' ] }
