app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type: annotation
    prefix: /

api:
    resource: "@ApiBundle/Controller/DefaultController.php"
    type:     annotation
    prefix: /api

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix: /user

# FOSUserBundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# ApiBundle
configurations:
    type:     rest
    resource: ApiBundle\Controller\SmartPackageConfigurationController
    prefix: /api

# AppBundle
places:
    type:     rest
    resource: AppBundle\Controller\PlaceController
    prefix: /api

prices:
    type:     rest
    resource: AppBundle\Controller\Place\PriceController
    prefix: /api

themes:
    type:     rest
    resource: AppBundle\Controller\Place\ThemeController
    prefix: /api

users:
    type:     rest
    resource: AppBundle\Controller\UserController
    prefix: /api

preferences:
    type:     rest
    resource: AppBundle\Controller\User\PreferenceController
    prefix: /api

auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController
    prefix: /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc
