user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix: /user

# FOSUserBundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# AppBundle
places:
    type:     rest
    resource: AppBundle\Controller\PlaceController
    prefix: /api

prices:
    type:     rest
    resource: AppBundle\Controller\Place\PriceController
    prefix: /api

themes:
    type:     rest
    resource: AppBundle\Controller\Place\ThemeController
    prefix: /api

users:
    type:     rest
    resource: UserBundle\Controller\UserController
    prefix: /api

preferences:
    type:     rest
    resource: AppBundle\Controller\User\PreferenceController
    prefix: /api

auth-tokens:
    type:     rest
    resource: UserBundle\Controller\AuthTokenController
    prefix: /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc
