#index:
#    path: /
#    controller: App\Controller\DefaultController::index

places:
    type:     rest
    resource: App\Controller\PlaceController
    prefix: /api

prices:
    type:     rest
    resource: App\Controller\Place\PriceController
    prefix: /api

themes:
    type:     rest
    resource: App\Controller\Place\ThemeController
    prefix: /api

users:
    type:     rest
    resource: App\Controller\UserController
    prefix: /api

preferences:
    type:     rest
    resource: App\Controller\User\PreferenceController
    prefix: /api

auth-tokens:
    type:     rest
    resource: App\Controller\AuthTokenController
    prefix: /api