homepage:
    type: attribute
    resource: App\Controller\ApiController
    prefix: /

places:
    type: attribute
    resource: App\Controller\PlaceController
    prefix: /api

prices:
    type: attribute
    resource: App\Controller\Place\PriceController
    prefix: /api

themes:
    type: attribute
    resource: App\Controller\Place\ThemeController
    prefix: /api

users:
    type: attribute
    resource: App\Controller\UserController
    prefix: /api

preferences:
    type: attribute
    resource: App\Controller\User\PreferenceController
    prefix: /api

auth-tokens:
    type: attribute
    resource: App\Controller\AuthTokenController
    prefix: /api
