# src/AppBundle/Resources/config/serializer/Entity.Price.yml
AppBundle\Entity\Price:
    exclusion_policy: none
    properties:
        id:
            groups: ['place', 'price']
        type:
            groups: ['place', 'price']
        value:
            groups: ['place', 'price']
        place:
            groups: ['price']
